wip: POC for adding interfaces to the templates
gofiber/template pull request #251
Opened 2023-05-10 22:44 UTC by mfiumara

Initial draft for having interfaces for template engines. This can reworked and is open for discussion.

applies to #248

2023-05-11 06:17 UTC, ReneWerner87 commented
@mfiumara thanks for the effort
the interface looks good, but the usage in the first engine does not

in many cases the engines have additional functionalities, so i think we have to export them as well

for the check if the engine complies with the interface i would suggest we use "embedded interfaces" or "typechecks in test or real code".

2023-05-11 10:48 UTC, mfiumara commented
Hi,

Thanks for the feedback I'll come up with a refinement of this draft later tonight by embedding interfaces. I see what you mean and we're indeed not exporting all functions of the engine right now.

2023-05-11 18:05 UTC, mfiumara commented
Hey I've added an embedded interface for Pug such that all functions are exported now.

For the remainder of the engines I'd go through all of them in a similar fashion. Let me know if anything else is required before I go through with that. Perhaps I should move the function comments inside the interface definition? Or copy them over?

2023-05-11 18:18 UTC, efectn reviewed
I think internal dir is not good idea. Someome else may want to use this interface in their projects. It can be template.go in the project root like how it's on storage repo

2023-05-11 18:35 UTC, ReneWerner87 commented
> I think internal dir is not good idea. Someome else may want to use this interface in their projects. It can be template.go in the project root like how it's on storage repo 

Yes, good point

2023-05-11 20:03 UTC, mfiumara commented
@efectn Moved to root into `template.go`.

2023-05-11 22:09 UTC, mfiumara commented
@efectn I've done the following:

- Added struct definition into internal: this should not be used by external packages as far as I understand
- The interface definition remains in the root (template.go)
- Individual engines can now embed the internal struct to have all basic methods promoted into their own interface type

I don't see the commit here yet in the PR, I'm not too familiar with Github but perhaps that takes some time to appear.

2023-05-11 23:00 UTC, mfiumara commented
Added second Engine Mustache to illustrate further. I should be able to do the rest fairly quickly let me know if this is the way forward.

2023-05-13 14:56 UTC, mfiumara commented
I think I'm done @efectn. Would be great if you can have a look.

2023-05-17 18:38 UTC, efectn commented
Can you check hound comments @mfiumara

2023-05-19 14:38 UTC, mfiumara commented
@efectn Done

2023-05-20 19:09 UTC, efectn commented
@mfiumara can you resolve the conflicts, i removed parse() from engines

2023-05-20 19:09 UTC, efectn approved these changes

2023-05-21 11:33 UTC, mfiumara commented
@efectn Rebased and squashed commits.

2023-05-21 12:04 UTC, efectn requested changes

2023-05-21 12:04 UTC, efectn commented on ace/ace.go
> +type engine struct {
I think we no longer need these

2023-05-21 12:04 UTC, efectn commented on slim/slim.go
>  func NewFileSystem(fs http.FileSystem, extension string) *Engine {
We should also add interface to Slim.

2023-05-21 15:08 UTC, efectn approved these changes

2023-05-22 17:39 UTC, efectn commented
> Hi @efectn could this be merged? I had to resolve conflicts again due to other changes being merged.

The changes are OK to me but we should wait for one more review. @ReneWerner87 will review the PR when he is free.

2023-05-23 10:03 UTC, ReneWerner87 commented
@mfiumara very good work

https://github.com/gofiber/template/pull/251#issuecomment-1543400484
> in many cases the engines have additional functionalities, so i think we have to export them as well

this fact is unfortunately not quite covered

try to explain it again
it can happen that an engine has additional methods beyond the basic functionality, which is totally ok
but currently they are not accessible, because you always return the general interface as return type of the "New" method
it's ok to return the original engine here, because internally it's ensured that it implements the methods of the interface and the users also have the possibility to pass the interface in their tests or methods

2023-05-23 10:10 UTC, ReneWerner87 commented
By the way, if you made the last change, do we have to count up the major because there is a breaking change included here ?

2023-05-24 09:27 UTC, merged